import { Footer, Header } from '@core/shared/ui';
import './global.css';

export const metadata = {
  title: 'Welcome to portfolio',
  description: 'Generated by create-nx-workspace',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <Header />
        {children} <Footer />
      </body>
    </html>
  );
}
